[workspace]
resolver = "3"
members = ["crates/core", "crates/desktop", "crates/winplayer"]
default-members = ["crates/desktop", "crates/core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
yt-lite-core = { path = "crates/core" }
yt-lite-winplayer = { path = "crates/winplayer" }
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"

# GPUI is very slow unoptimized; optimize dependencies even in dev.
[profile.dev.package."*"]
opt-level = 2
