#!/usr/bin/env bash
# Builds the Rust core for Android and prepares the Gradle project:
#   android/app/src/main/jniLibs/<abi>/libyt_lite_ffi.so   the core
#   android/app/src/main/java/uniffi/yt_lite_ffi/*.kt      UniFFI Kotlin bindings
#   android/secrets.properties                             Google OAuth client, copied
#                                                          from the desktop config
# All three are generated (gitignored). Run this before opening android/ in Android
# Studio or running ./gradlew, and again after changing Rust code.
#
# YT_LITE_ANDROID_ABIS (default arm64-v8a, which covers current phones and the
# emulator on Apple silicon) can add x86_64 or armeabi-v7a; install their Rust
# targets with `rustup target add x86_64-linux-android armv7-linux-androideabi`.
set -euo pipefail
cd "$(dirname "$0")/.."

# Must match minSdk in android/app/build.gradle.kts.
MIN_SDK=28
ABIS="${YT_LITE_ANDROID_ABIS:-arm64-v8a}"
SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
NDK="${ANDROID_NDK_HOME:-$(ls -d "$SDK"/ndk/* 2>/dev/null | sort -V | tail -1)}"
if [[ ! -d "$NDK" ]]; then
  echo "Android NDK not found. Install it in Android Studio (Settings → SDK Manager → SDK Tools →" >&2
  echo "NDK) or set ANDROID_NDK_HOME." >&2
  exit 1
fi
TOOLCHAIN="$(ls -d "$NDK"/toolchains/llvm/prebuilt/*/bin | head -1)"
JNI_LIBS=android/app/src/main/jniLibs

for abi in $ABIS; do
  case "$abi" in
    arm64-v8a) target=aarch64-linux-android; clang=aarch64-linux-android ;;
    x86_64) target=x86_64-linux-android; clang=x86_64-linux-android ;;
    armeabi-v7a) target=armv7-linux-androideabi; clang=armv7a-linux-androideabi ;;
    *) echo "unknown ABI: $abi" >&2; exit 1 ;;
  esac
  echo "==> Building Rust core for $abi"
  env_target=$(echo "$target" | tr 'a-z-' 'A-Z_')
  cc="$TOOLCHAIN/$clang$MIN_SDK-clang"
  # C parts (ring, SQLite) use the NDK's clang; 16 KB page alignment is required
  # on Android 15+ devices with 16 KB pages, and by Google Play.
  env "CC_${target//-/_}=$cc" "AR_${target//-/_}=$TOOLCHAIN/llvm-ar" \
    "CARGO_TARGET_${env_target}_LINKER=$cc" \
    "CARGO_TARGET_${env_target}_RUSTFLAGS=-C link-arg=-Wl,-z,max-page-size=16384" \
    cargo rustc -p yt-lite-ffi --lib --release --target "$target" --crate-type cdylib
  mkdir -p "$JNI_LIBS/$abi"
  cp "target/$target/release/libyt_lite_ffi.so" "$JNI_LIBS/$abi/"
done

echo "==> Generating Kotlin bindings"
cargo build -p yt-lite-ffi
rm -rf android/app/src/main/java/uniffi
cargo run -q -p yt-lite-ffi --bin uniffi-bindgen -- generate \
  --library target/debug/libyt_lite_ffi.dylib --language kotlin \
  --out-dir android/app/src/main/java --no-format

echo "==> Writing android/secrets.properties"
CONFIG="${YT_LITE_CONFIG:-$HOME/Library/Application Support/yt-lite/config.toml}"
python3 - "$CONFIG" <<'PY'
import sys, tomllib
client_id = client_secret = ""
try:
    with open(sys.argv[1], "rb") as f:
        g = tomllib.load(f).get("google", {})
    client_id, client_secret = g.get("client_id", ""), g.get("client_secret", "")
except FileNotFoundError:
    pass
with open("android/secrets.properties", "w") as out:
    out.write("# Generated by scripts/build-android.sh from the desktop config.toml. Do not commit.\n")
    out.write(f"google.clientId={client_id}\n")
    out.write(f"google.clientSecret={client_secret}\n")
print("    Google client:", "found" if client_id else "not configured (Subscriptions sign-in disabled)")
PY
echo "Done. Open android/ in Android Studio, or: cd android && ./gradlew installDebug"
