#!/usr/bin/env bash
# Builds the Rust core for iOS and prepares the Xcode project:
#   ios/Generated/YtLiteCore.xcframework   static libs (device + simulator) + C headers
#   ios/YtLite/Generated/YtLiteFFI.swift   UniFFI Swift bindings
#   ios/YtLite/Secrets.swift               Google OAuth client, copied from the desktop config
# All three are generated (gitignored). Run this before opening ios/YtLite.xcodeproj, and again
# after changing Rust code.
set -euo pipefail
cd "$(dirname "$0")/.."

PROFILE=ios-release
# Must match IPHONEOS_DEPLOYMENT_TARGET in the Xcode project; also used by the
# C parts (ring, SQLite) so they don't target the newest SDK only.
export IPHONEOS_DEPLOYMENT_TARGET=17.0
GEN=ios/Generated
BINDINGS="$GEN/bindings"
HEADERS="$GEN/headers"

echo "==> Building Rust core (device + simulator)"
cargo build -p yt-lite-ffi --profile "$PROFILE" --target aarch64-apple-ios
cargo build -p yt-lite-ffi --profile "$PROFILE" --target aarch64-apple-ios-sim

echo "==> Generating Swift bindings"
cargo build -p yt-lite-ffi
rm -rf "$BINDINGS" "$HEADERS"
cargo run -q -p yt-lite-ffi --bin uniffi-bindgen -- generate \
  --library target/debug/libyt_lite_ffi.dylib --language swift --out-dir "$BINDINGS"
mkdir -p "$HEADERS" ios/YtLite/Generated
cp "$BINDINGS/yt_lite_ffiFFI.h" "$HEADERS/"
cp "$BINDINGS/yt_lite_ffiFFI.modulemap" "$HEADERS/module.modulemap"
cp "$BINDINGS/yt_lite_ffi.swift" ios/YtLite/Generated/YtLiteFFI.swift

echo "==> Packaging $GEN/YtLiteCore.xcframework"
rm -rf "$GEN/YtLiteCore.xcframework"
xcodebuild -create-xcframework \
  -library "target/aarch64-apple-ios/$PROFILE/libyt_lite_ffi.a" -headers "$HEADERS" \
  -library "target/aarch64-apple-ios-sim/$PROFILE/libyt_lite_ffi.a" -headers "$HEADERS" \
  -output "$GEN/YtLiteCore.xcframework" >/dev/null

echo "==> Writing ios/YtLite/Secrets.swift"
CONFIG="${YT_LITE_CONFIG:-$HOME/Library/Application Support/yt-lite/config.toml}"
python3 - "$CONFIG" <<'PY'
import sys, tomllib, json
client_id = client_secret = ""
try:
    with open(sys.argv[1], "rb") as f:
        g = tomllib.load(f).get("google", {})
    client_id, client_secret = g.get("client_id", ""), g.get("client_secret", "")
except FileNotFoundError:
    pass
with open("ios/YtLite/Secrets.swift", "w") as out:
    out.write("// Generated by scripts/build-ios.sh from the desktop config.toml. Do not commit.\n")
    out.write("enum Secrets {\n")
    out.write(f"    static let googleClientId = {json.dumps(client_id)}\n")
    out.write(f"    static let googleClientSecret = {json.dumps(client_secret)}\n")
    out.write("}\n")
print("    Google client:", "found" if client_id else "not configured (Subscriptions sign-in disabled)")
PY
echo "Done. Open ios/YtLite.xcodeproj"
